version: '3.3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./production:/production
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
      build: .
      volumes:
        - ./production:/production